/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package carrefour;

import java.awt.Color;
import java.awt.Container;
import java.awt.FlowLayout;
import java.awt.Font;
import java.awt.event.MouseEvent;
import java.awt.event.MouseListener;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JPanel;

/**
 *
 * @author Windows 10
 */
public class ClientForm extends javax.swing.JFrame {

   
    /**
     * Creates new form ClienyForm
     */
    public ClientForm() {
        initComponents();
        // Remove All Panals from home panal
        homePanal.removeAll();
        homePanal.repaint();
        homePanal.revalidate();
       
        addProductPanal.removeAll();
        addProductPanal.repaint();
        addProductPanal.revalidate();
        //JLabel []JlabelButtone = {homeLable,mailLable,aboutLable,generalLable,payLable,saleLable,infoLable}; 
        JLabel [] openLabel = {lhome,labout,lgeneral,linfo,lmail,lsale,lpayment};
       
        for (JLabel jLabel : openLabel) {
            jLabel.setFont(new Font("Verdana",Font.PLAIN, 11));
           
            jLabel.setForeground(new Color(241,62,51));
            jLabel.setHorizontalAlignment((int) CENTER_ALIGNMENT);
           
        }
      
       
        
        
      // JButton [] button = {HomeButton,mailButton,paymentButton,generalButton,saleButton,infoButton,aboutButton};
//        for (JButton jButton : button) {
//            jButton.setForeground(new Color(241,62,51));
//            jButton.setBackground(new Color(36,40,44));
//            jButton.addMouseListener(new MouseListener() {
//                @Override
//                public void mouseClicked(MouseEvent e) {
//
//                }
//
//                @Override
//                public void mousePressed(MouseEvent e) {
//                    
//                }
//
//                @Override
//                public void mouseReleased(MouseEvent e) {
//                }
//
//                @Override
//                public void mouseEntered(MouseEvent e) {
//                    jButton.setBackground(new Color(0,63,138));
//                }
//
//                @Override
//                public void mouseExited(MouseEvent e) {
//                    jButton.setBackground(new Color(36,40,44));
//
//                }
//            });
//            
//        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        sideMenu = new javax.swing.JPanel();
        Logo = new javax.swing.JLabel();
        homeLable = new javax.swing.JLabel();
        payLable = new javax.swing.JLabel();
        saleLable = new javax.swing.JLabel();
        infoLable = new javax.swing.JLabel();
        aboutLable = new javax.swing.JLabel();
        mailLable = new javax.swing.JLabel();
        generalLable = new javax.swing.JLabel();
        lhome = new javax.swing.JLabel();
        lmail = new javax.swing.JLabel();
        lpayment = new javax.swing.JLabel();
        lgeneral = new javax.swing.JLabel();
        lsale = new javax.swing.JLabel();
        linfo = new javax.swing.JLabel();
        labout = new javax.swing.JLabel();
        centerBackground = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        nameLable = new javax.swing.JLabel();
        nameLable1 = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        jPanel10 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        tableAdd = new javax.swing.JLabel();
        addProductPanal = new javax.swing.JPanel();
        productTablePanal = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel4 = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        tableToAdd = new javax.swing.JLabel();
        viewTable = new javax.swing.JLabel();
        homePanal = new javax.swing.JPanel();
        mailPanal = new javax.swing.JPanel();
        paymentPanal = new javax.swing.JPanel();
        generalPanal = new javax.swing.JPanel();
        salePanal = new javax.swing.JPanel();
        infoPanal = new javax.swing.JPanel();
        aboutPanal = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Carrefour - Multinational Corporation (Client)");
        setPreferredSize(new java.awt.Dimension(1080, 650));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setPreferredSize(new java.awt.Dimension(913, 100));
        jPanel2.setLayout(new java.awt.BorderLayout());

        sideMenu.setBackground(new java.awt.Color(21, 25, 28));
        sideMenu.setPreferredSize(new java.awt.Dimension(100, 700));

        Logo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/5a0c72729642de34b6b65ce7.png"))); // NOI18N
        Logo.setPreferredSize(new java.awt.Dimension(140, 100));

        homeLable.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        homeLable.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/home_35px.png"))); // NOI18N
        homeLable.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        homeLable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                homeLableMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                homeLableMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                homeLableMouseExited(evt);
            }
        });

        payLable.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        payLable.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/coins_35px.png"))); // NOI18N
        payLable.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        payLable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                payLableMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                payLableMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                payLableMouseExited(evt);
            }
        });

        saleLable.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        saleLable.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/shopping_cart_35px.png"))); // NOI18N
        saleLable.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        saleLable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                saleLableMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                saleLableMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                saleLableMouseExited(evt);
            }
        });

        infoLable.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        infoLable.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/information_35px.png"))); // NOI18N
        infoLable.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        infoLable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                infoLableMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                infoLableMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                infoLableMouseExited(evt);
            }
        });

        aboutLable.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        aboutLable.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/about_35px.png"))); // NOI18N
        aboutLable.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        aboutLable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                aboutLableMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                aboutLableMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                aboutLableMouseExited(evt);
            }
        });

        mailLable.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        mailLable.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/email_35px.png"))); // NOI18N
        mailLable.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        mailLable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mailLableMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                mailLableMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                mailLableMouseExited(evt);
            }
        });

        generalLable.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        generalLable.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/profile_35px.png"))); // NOI18N
        generalLable.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        generalLable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                generalLableMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                generalLableMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                generalLableMouseExited(evt);
            }
        });

        lhome.setFont(new java.awt.Font("Tahoma", 2, 11)); // NOI18N
        lhome.setForeground(new java.awt.Color(255, 0, 0));

        lmail.setFont(new java.awt.Font("Tahoma", 2, 11)); // NOI18N
        lmail.setForeground(new java.awt.Color(255, 0, 0));

        lpayment.setFont(new java.awt.Font("Tahoma", 2, 11)); // NOI18N
        lpayment.setForeground(new java.awt.Color(255, 0, 0));

        lgeneral.setFont(new java.awt.Font("Tahoma", 2, 11)); // NOI18N
        lgeneral.setForeground(new java.awt.Color(255, 0, 0));

        lsale.setFont(new java.awt.Font("Tahoma", 2, 11)); // NOI18N
        lsale.setForeground(new java.awt.Color(255, 0, 0));

        linfo.setFont(new java.awt.Font("Tahoma", 2, 11)); // NOI18N
        linfo.setForeground(new java.awt.Color(255, 0, 0));

        labout.setFont(new java.awt.Font("Tahoma", 2, 11)); // NOI18N
        labout.setForeground(new java.awt.Color(255, 0, 0));

        javax.swing.GroupLayout sideMenuLayout = new javax.swing.GroupLayout(sideMenu);
        sideMenu.setLayout(sideMenuLayout);
        sideMenuLayout.setHorizontalGroup(
            sideMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(homeLable, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
            .addComponent(mailLable, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(payLable, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(Logo, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
            .addComponent(saleLable, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(generalLable, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(lhome, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(lmail, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(lpayment, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(lgeneral, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(lsale, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(linfo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(infoLable, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(aboutLable, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(labout, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        sideMenuLayout.setVerticalGroup(
            sideMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sideMenuLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(Logo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addComponent(homeLable)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lhome)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(mailLable)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lmail)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(payLable)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lpayment)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(generalLable)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lgeneral)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(saleLable)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lsale)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(infoLable, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(linfo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(aboutLable, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labout)
                .addContainerGap())
        );

        jPanel2.add(sideMenu, java.awt.BorderLayout.WEST);

        centerBackground.setBackground(new java.awt.Color(36, 40, 44));
        centerBackground.setLayout(new java.awt.BorderLayout());
        centerBackground.add(jLabel1, java.awt.BorderLayout.CENTER);

        jPanel1.setBackground(new java.awt.Color(36, 40, 44));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(20, 25, 28)));
        jPanel1.setPreferredSize(new java.awt.Dimension(813, 150));
        jPanel1.setLayout(new java.awt.GridLayout(1, 0));

        jPanel5.setBackground(new java.awt.Color(20, 25, 28));

        nameLable.setBackground(new java.awt.Color(182, 182, 179));
        nameLable.setFont(new java.awt.Font("Perpetua Titling MT", 0, 22)); // NOI18N
        nameLable.setForeground(new java.awt.Color(182, 182, 179));
        nameLable.setText("Nabeel Yousaf");

        nameLable1.setBackground(new java.awt.Color(182, 182, 179));
        nameLable1.setFont(new java.awt.Font("Perpetua Titling MT", 0, 14)); // NOI18N
        nameLable1.setForeground(new java.awt.Color(182, 182, 179));
        nameLable1.setText("shop name");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(nameLable, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nameLable1, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 25, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(nameLable)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(nameLable1)
                .addContainerGap(92, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel5);

        jPanel9.setBackground(new java.awt.Color(20, 25, 28));

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 287, Short.MAX_VALUE)
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 148, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel9);

        jPanel10.setBackground(new java.awt.Color(20, 25, 28));

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 287, Short.MAX_VALUE)
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 148, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel10);

        centerBackground.add(jPanel1, java.awt.BorderLayout.PAGE_START);

        jPanel3.setPreferredSize(new java.awt.Dimension(813, 250));
        jPanel3.setLayout(new java.awt.BorderLayout());
        jPanel3.add(jLabel2, java.awt.BorderLayout.CENTER);

        jPanel6.setBackground(new java.awt.Color(36, 40, 44));
        jPanel6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(20, 25, 28)));
        jPanel6.setPreferredSize(new java.awt.Dimension(815, 70));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/icons8_location_off_50px_1.png"))); // NOI18N

        jLabel3.setBackground(new java.awt.Color(182, 182, 179));
        jLabel3.setForeground(new java.awt.Color(182, 182, 179));
        jLabel3.setText("Nabeel Yousaf");

        jLabel5.setBackground(new java.awt.Color(182, 182, 179));
        jLabel5.setForeground(new java.awt.Color(182, 182, 179));
        jLabel5.setText("2020-CS-103");

        jLabel6.setBackground(new java.awt.Color(182, 182, 179));
        jLabel6.setForeground(new java.awt.Color(182, 182, 179));
        jLabel6.setText("Haider Ali");

        jLabel7.setBackground(new java.awt.Color(182, 182, 179));
        jLabel7.setForeground(new java.awt.Color(182, 182, 179));
        jLabel7.setText("2020-CS-137");

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/icons8_location_off_50px_1.png"))); // NOI18N

        tableAdd.setBackground(new java.awt.Color(182, 182, 179));
        tableAdd.setFont(new java.awt.Font("Perpetua", 0, 18)); // NOI18N
        tableAdd.setForeground(new java.awt.Color(241, 62, 51));

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(66, 66, 66)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel5))
                .addGap(126, 126, 126)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7))
                .addGap(126, 126, 126)
                .addComponent(tableAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(191, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel5)
                        .addGap(6, 6, 6))
                    .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(tableAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        jPanel3.add(jPanel6, java.awt.BorderLayout.PAGE_END);

        addProductPanal.setBackground(new java.awt.Color(36, 40, 44));
        addProductPanal.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(20, 25, 28)));
        addProductPanal.setLayout(new java.awt.GridLayout(1, 0));

        productTablePanal.setBackground(new java.awt.Color(36, 40, 44));
        productTablePanal.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(20, 25, 28)));
        productTablePanal.setLayout(new java.awt.BorderLayout());

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        productTablePanal.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        addProductPanal.add(productTablePanal);

        jPanel3.add(addProductPanal, java.awt.BorderLayout.CENTER);

        centerBackground.add(jPanel3, java.awt.BorderLayout.PAGE_END);

        jPanel4.setBackground(new java.awt.Color(36, 40, 44));
        jPanel4.setPreferredSize(new java.awt.Dimension(200, 365));
        jPanel4.setLayout(new java.awt.GridLayout(1, 0));

        jPanel8.setBackground(new java.awt.Color(20, 25, 28));
        jPanel8.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(20, 25, 28)));
        jPanel8.setLayout(new java.awt.BorderLayout());

        tableToAdd.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        tableToAdd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/icons8_click_&_collect_35px_2.png"))); // NOI18N
        tableToAdd.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        tableToAdd.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableToAddMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                tableToAddMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                tableToAddMouseExited(evt);
            }
        });
        jPanel8.add(tableToAdd, java.awt.BorderLayout.PAGE_END);

        viewTable.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        viewTable.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/icons8_table_properties_35px.png"))); // NOI18N
        viewTable.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        viewTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                viewTableMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                viewTableMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                viewTableMouseExited(evt);
            }
        });
        jPanel8.add(viewTable, java.awt.BorderLayout.PAGE_END);

        jPanel4.add(jPanel8);

        centerBackground.add(jPanel4, java.awt.BorderLayout.LINE_END);

        homePanal.setBackground(new java.awt.Color(36, 40, 44));
        homePanal.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(20, 25, 28)));
        homePanal.setAutoscrolls(true);
        homePanal.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        homePanal.setPreferredSize(new java.awt.Dimension(500, 365));
        homePanal.setLayout(new java.awt.BorderLayout());

        mailPanal.setBackground(new java.awt.Color(1, 1, 1));
        mailPanal.setAutoscrolls(true);
        mailPanal.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        mailPanal.setPreferredSize(new java.awt.Dimension(500, 365));

        javax.swing.GroupLayout mailPanalLayout = new javax.swing.GroupLayout(mailPanal);
        mailPanal.setLayout(mailPanalLayout);
        mailPanalLayout.setHorizontalGroup(
            mailPanalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        mailPanalLayout.setVerticalGroup(
            mailPanalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        homePanal.add(mailPanal, java.awt.BorderLayout.CENTER);

        paymentPanal.setBackground(new java.awt.Color(255, 2, 2));
        paymentPanal.setAutoscrolls(true);
        paymentPanal.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        paymentPanal.setPreferredSize(new java.awt.Dimension(500, 365));

        javax.swing.GroupLayout paymentPanalLayout = new javax.swing.GroupLayout(paymentPanal);
        paymentPanal.setLayout(paymentPanalLayout);
        paymentPanalLayout.setHorizontalGroup(
            paymentPanalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        paymentPanalLayout.setVerticalGroup(
            paymentPanalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        homePanal.add(paymentPanal, java.awt.BorderLayout.CENTER);

        generalPanal.setBackground(new java.awt.Color(0, 0, 255));
        generalPanal.setAutoscrolls(true);
        generalPanal.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        generalPanal.setPreferredSize(new java.awt.Dimension(500, 365));

        javax.swing.GroupLayout generalPanalLayout = new javax.swing.GroupLayout(generalPanal);
        generalPanal.setLayout(generalPanalLayout);
        generalPanalLayout.setHorizontalGroup(
            generalPanalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        generalPanalLayout.setVerticalGroup(
            generalPanalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        homePanal.add(generalPanal, java.awt.BorderLayout.CENTER);

        salePanal.setBackground(new java.awt.Color(100, 1, 1));
        salePanal.setAutoscrolls(true);
        salePanal.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        salePanal.setPreferredSize(new java.awt.Dimension(500, 365));

        javax.swing.GroupLayout salePanalLayout = new javax.swing.GroupLayout(salePanal);
        salePanal.setLayout(salePanalLayout);
        salePanalLayout.setHorizontalGroup(
            salePanalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        salePanalLayout.setVerticalGroup(
            salePanalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        homePanal.add(salePanal, java.awt.BorderLayout.CENTER);

        infoPanal.setBackground(new java.awt.Color(200, 100, 1));
        infoPanal.setAutoscrolls(true);
        infoPanal.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        infoPanal.setPreferredSize(new java.awt.Dimension(500, 365));

        javax.swing.GroupLayout infoPanalLayout = new javax.swing.GroupLayout(infoPanal);
        infoPanal.setLayout(infoPanalLayout);
        infoPanalLayout.setHorizontalGroup(
            infoPanalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        infoPanalLayout.setVerticalGroup(
            infoPanalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        homePanal.add(infoPanal, java.awt.BorderLayout.CENTER);

        aboutPanal.setBackground(new java.awt.Color(150, 150, 4));
        aboutPanal.setAutoscrolls(true);
        aboutPanal.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        aboutPanal.setPreferredSize(new java.awt.Dimension(500, 365));

        javax.swing.GroupLayout aboutPanalLayout = new javax.swing.GroupLayout(aboutPanal);
        aboutPanal.setLayout(aboutPanalLayout);
        aboutPanalLayout.setHorizontalGroup(
            aboutPanalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 661, Short.MAX_VALUE)
        );
        aboutPanalLayout.setVerticalGroup(
            aboutPanalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        homePanal.add(aboutPanal, java.awt.BorderLayout.CENTER);

        jLabel9.setText("jLabel9");
        homePanal.add(jLabel9, java.awt.BorderLayout.PAGE_START);

        centerBackground.add(homePanal, java.awt.BorderLayout.CENTER);

        jPanel2.add(centerBackground, java.awt.BorderLayout.CENTER);

        getContentPane().add(jPanel2, java.awt.BorderLayout.CENTER);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void homeLableMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_homeLableMouseEntered
        // TODO add your handling code here:
        homeLable.setBackground(new Color(36,40,44));
        homeLable.setOpaque(true);
        lhome.setText("Home");
        
        
    }//GEN-LAST:event_homeLableMouseEntered

    private void homeLableMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_homeLableMouseExited
        // TODO add your handling code here:
        
        
        lhome.setText("");
        homeLable.setBackground(new Color(20,25,28));
        homeLable.setOpaque(false);
        
    }//GEN-LAST:event_homeLableMouseExited

    private void mailLableMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mailLableMouseEntered
        // TODO add your handling code here:
        mailLable.setBackground(new Color(36,40,44));
        mailLable.setOpaque(true);
        lmail.setText("Email");
    }//GEN-LAST:event_mailLableMouseEntered

    private void mailLableMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mailLableMouseExited
        // TODO add your handling code here:
        mailLable.setBackground(new Color(20,25,28));
        mailLable.setOpaque(false);
        lmail.setText("");
    }//GEN-LAST:event_mailLableMouseExited

    private void payLableMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_payLableMouseEntered
        // TODO add your handling code here:
       payLable.setBackground(new Color(36,40,44));
        payLable.setOpaque(true);
        lpayment.setText("Payment");
    }//GEN-LAST:event_payLableMouseEntered

    private void payLableMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_payLableMouseExited
        // TODO add your handling code here:
        payLable.setBackground(new Color(20,25,28));
        payLable.setOpaque(false);
        lpayment.setText("");
       
    }//GEN-LAST:event_payLableMouseExited

    private void generalLableMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_generalLableMouseEntered
        // TODO add your handling code here:
        generalLable.setBackground(new Color(36,40,44));
        generalLable.setOpaque(true);
        lgeneral.setText("General");
    }//GEN-LAST:event_generalLableMouseEntered

    private void generalLableMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_generalLableMouseExited
        // TODO add your handling code here:
        generalLable.setBackground(new Color(20,25,28));
        generalLable.setOpaque(false);
        lgeneral.setText("");
    }//GEN-LAST:event_generalLableMouseExited

    private void saleLableMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_saleLableMouseEntered
        // TODO add your handling code here:
        saleLable.setBackground(new Color(36,40,44));
        saleLable.setOpaque(true);
        lsale.setText("Sale");
    }//GEN-LAST:event_saleLableMouseEntered

    private void saleLableMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_saleLableMouseExited
        // TODO add your handling code here:
        saleLable.setBackground(new Color(20,25,28));
        saleLable.setOpaque(false);
        lsale.setText("");
    }//GEN-LAST:event_saleLableMouseExited

    private void infoLableMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_infoLableMouseEntered
        // TODO add your handling code here:
        infoLable.setBackground(new Color(36,40,44));
        infoLable.setOpaque(true);
        linfo.setText("Info");
    }//GEN-LAST:event_infoLableMouseEntered

    private void infoLableMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_infoLableMouseExited
        // TODO add your handling code here:
        infoLable.setBackground(new Color(20,25,28));
        infoLable.setOpaque(false);
         linfo.setText("");
       
    }//GEN-LAST:event_infoLableMouseExited

    private void aboutLableMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_aboutLableMouseEntered
        // TODO add your handling code here:
        aboutLable.setBackground(new Color(36,40,44));
        aboutLable.setOpaque(true);
        labout.setText("About");
    }//GEN-LAST:event_aboutLableMouseEntered

    private void aboutLableMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_aboutLableMouseExited
        // TODO add your handling code here:
        aboutLable.setBackground(new Color(20,25,28));
        aboutLable.setOpaque(false);
        
        labout.setText("");
    }//GEN-LAST:event_aboutLableMouseExited

    private void homeLableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_homeLableMouseClicked
        // TODO add your handling code here:
//        removing panals
        homePanal.removeAll();
        homePanal.repaint();
        homePanal.revalidate();
        
    }//GEN-LAST:event_homeLableMouseClicked

    private void mailLableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mailLableMouseClicked
        // TODO add your handling code here:
        homePanal.removeAll();
        homePanal.repaint();
        homePanal.revalidate();
        
        homePanal.add(mailPanal);
        homePanal.repaint();
        homePanal.revalidate();
        
    }//GEN-LAST:event_mailLableMouseClicked

    private void payLableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_payLableMouseClicked
        // TODO add your handling code here:
        homePanal.removeAll();
        homePanal.repaint();
        homePanal.revalidate();
        //Adding panals
        homePanal.add(paymentPanal);
        homePanal.repaint();
        homePanal.revalidate();
    }//GEN-LAST:event_payLableMouseClicked

    private void generalLableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_generalLableMouseClicked
        // TODO add your handling code here:
        homePanal.removeAll();
        homePanal.repaint();
        homePanal.revalidate();
        //Adding panals
        homePanal.add(generalPanal);
        homePanal.repaint();
        homePanal.revalidate();
    }//GEN-LAST:event_generalLableMouseClicked

    private void saleLableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_saleLableMouseClicked
        // TODO add your handling code here:
        homePanal.removeAll();
        homePanal.repaint();
        homePanal.revalidate();
        //Adding panals
        homePanal.add(salePanal);
        homePanal.repaint();
        homePanal.revalidate();
    }//GEN-LAST:event_saleLableMouseClicked

    private void infoLableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_infoLableMouseClicked
        // TODO add your handling code here:
        homePanal.removeAll();
        homePanal.repaint();
        homePanal.revalidate();
        //Adding panals
        homePanal.add(infoPanal);
        homePanal.repaint();
        homePanal.revalidate();
    }//GEN-LAST:event_infoLableMouseClicked

    private void aboutLableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_aboutLableMouseClicked
        // TODO add your handling code here:
        homePanal.removeAll();
        homePanal.repaint();
        homePanal.revalidate();
        //Adding panals
        homePanal.add(aboutPanal);
        homePanal.repaint();
        homePanal.revalidate();
    }//GEN-LAST:event_aboutLableMouseClicked

    private void tableToAddMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableToAddMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_tableToAddMouseExited

    private void tableToAddMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableToAddMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_tableToAddMouseEntered

    private void tableToAddMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableToAddMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_tableToAddMouseClicked

    private void viewTableMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_viewTableMouseExited
        // TODO add your handling code here:
        viewTable.setBackground(new Color(20,25,28));
        viewTable.setOpaque(false);
        tableAdd.setText("");
    }//GEN-LAST:event_viewTableMouseExited

    private void viewTableMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_viewTableMouseEntered
        // TODO add your handling code here:
        viewTable.setBackground(new Color(36,40,44));
        viewTable.setOpaque(true);
        tableAdd.setText("View Table");

    }//GEN-LAST:event_viewTableMouseEntered

    private void viewTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_viewTableMouseClicked
        // TODO add your handling code here:
        productTablePanal.setVisible(true);
        viewTable.setVisible(false);
        addProductPanal.add(productTablePanal);
        addProductPanal.repaint();
        addProductPanal.revalidate();
        tableToAdd.setVisible(true);
        tableToAdd.setEnabled(true);
    }//GEN-LAST:event_viewTableMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ClientForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ClientForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ClientForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ClientForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ClientForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Logo;
    private javax.swing.JLabel aboutLable;
    private javax.swing.JPanel aboutPanal;
    private javax.swing.JPanel addProductPanal;
    private javax.swing.JPanel centerBackground;
    private javax.swing.JLabel generalLable;
    private javax.swing.JPanel generalPanal;
    private javax.swing.JLabel homeLable;
    private javax.swing.JPanel homePanal;
    private javax.swing.JLabel infoLable;
    private javax.swing.JPanel infoPanal;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel labout;
    private javax.swing.JLabel lgeneral;
    private javax.swing.JLabel lhome;
    private javax.swing.JLabel linfo;
    private javax.swing.JLabel lmail;
    private javax.swing.JLabel lpayment;
    private javax.swing.JLabel lsale;
    private javax.swing.JLabel mailLable;
    private javax.swing.JPanel mailPanal;
    private javax.swing.JLabel nameLable;
    private javax.swing.JLabel nameLable1;
    private javax.swing.JLabel payLable;
    private javax.swing.JPanel paymentPanal;
    private javax.swing.JPanel productTablePanal;
    private javax.swing.JLabel saleLable;
    private javax.swing.JPanel salePanal;
    private javax.swing.JPanel sideMenu;
    private javax.swing.JLabel tableAdd;
    private javax.swing.JLabel tableToAdd;
    private javax.swing.JLabel viewTable;
    // End of variables declaration//GEN-END:variables
}
