/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package carrefour;

import java.awt.Color;
import java.awt.Container;
import java.awt.FlowLayout;
import java.awt.Font;
import java.awt.event.MouseEvent;
import java.awt.event.MouseListener;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JPanel;

/**
 *
 * @author Windows 10
 */
public class ManagerForm extends javax.swing.JFrame {

   
    /**
     * Creates new form ClienyForm
     */
    public ManagerForm() {
        initComponents();
        SearchPannel.removeAll();
        SearchPannel.repaint();
        SearchPannel.revalidate();
        // Remove All Panals from home panal
        homePanal.removeAll();
        homePanal.repaint();
        homePanal.revalidate();
       
        addProductPanal.removeAll();
        addProductPanal.repaint();
        addProductPanal.revalidate();
        //JLabel []JlabelButtone = {homeLable,mailLable,aboutLable,generalLable,payLable,saleLable,infoLable}; 
        JLabel [] openLabel = {lhome,lsale,lclient,lmail,lshop,lreq};
       
        for (JLabel jLabel : openLabel) {
            jLabel.setFont(new Font("Verdana",Font.PLAIN, 11));
           
            jLabel.setForeground(new Color(241,62,51));
            jLabel.setHorizontalAlignment((int) CENTER_ALIGNMENT);
           
        }
      
       
        
        
      // JButton [] button = {HomeButton,mailButton,paymentButton,generalButton,saleButton,infoButton,aboutButton};
//        for (JButton jButton : button) {
//            jButton.setForeground(new Color(241,62,51));
//            jButton.setBackground(new Color(36,40,44));
//            jButton.addMouseListener(new MouseListener() {
//                @Override
//                public void mouseClicked(MouseEvent e) {
//
//                }
//
//                @Override
//                public void mousePressed(MouseEvent e) {
//                    
//                }
//
//                @Override
//                public void mouseReleased(MouseEvent e) {
//                }
//
//                @Override
//                public void mouseEntered(MouseEvent e) {
//                    jButton.setBackground(new Color(0,63,138));
//                }
//
//                @Override
//                public void mouseExited(MouseEvent e) {
//                    jButton.setBackground(new Color(36,40,44));
//
//                }
//            });
//            
//        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        sideMenu = new javax.swing.JPanel();
        Logo = new javax.swing.JLabel();
        homeLable = new javax.swing.JLabel();
        payLable = new javax.swing.JLabel();
        saleLable = new javax.swing.JLabel();
        aboutLable = new javax.swing.JLabel();
        mailLable = new javax.swing.JLabel();
        generalLable = new javax.swing.JLabel();
        lhome = new javax.swing.JLabel();
        lmail = new javax.swing.JLabel();
        lreq = new javax.swing.JLabel();
        lclient = new javax.swing.JLabel();
        lshop = new javax.swing.JLabel();
        lsale = new javax.swing.JLabel();
        stafflabel = new javax.swing.JLabel();
        lstaff = new javax.swing.JLabel();
        jLabel50 = new javax.swing.JLabel();
        lrent = new javax.swing.JLabel();
        centerBackground = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        nameLable = new javax.swing.JLabel();
        nameLable1 = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jPanel10 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        tableAdd = new javax.swing.JLabel();
        addProductPanal = new javax.swing.JPanel();
        productTablePanal = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel4 = new javax.swing.JPanel();
        SearchPannel = new javax.swing.JPanel();
        tableToAdd = new javax.swing.JLabel();
        viewTable = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        infoPane = new javax.swing.JPanel();
        jLabel37 = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        jLabel39 = new javax.swing.JLabel();
        jLabel40 = new javax.swing.JLabel();
        jLabel41 = new javax.swing.JLabel();
        jLabel42 = new javax.swing.JLabel();
        jLabel43 = new javax.swing.JLabel();
        jLabel44 = new javax.swing.JLabel();
        jLabel45 = new javax.swing.JLabel();
        viewTable3 = new javax.swing.JLabel();
        searchRent = new javax.swing.JPanel();
        jLabel51 = new javax.swing.JLabel();
        jLabel52 = new javax.swing.JLabel();
        jLabel54 = new javax.swing.JLabel();
        jLabel55 = new javax.swing.JLabel();
        jLabel56 = new javax.swing.JLabel();
        jLabel57 = new javax.swing.JLabel();
        jLabel58 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        homePanal = new javax.swing.JPanel();
        mailPanal = new javax.swing.JPanel();
        ename4 = new javax.swing.JTextField();
        jLabel46 = new javax.swing.JLabel();
        jLabel47 = new javax.swing.JLabel();
        ename5 = new javax.swing.JTextField();
        jLabel48 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jButton17 = new javax.swing.JButton();
        jLabel49 = new javax.swing.JLabel();
        requestsPanal = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        ename = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        ename1 = new javax.swing.JTextField();
        ename2 = new javax.swing.JTextField();
        ename3 = new javax.swing.JTextField();
        jButton15 = new javax.swing.JButton();
        jLabel53 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jButton16 = new javax.swing.JButton();
        jLabel26 = new javax.swing.JLabel();
        shopPanal = new javax.swing.JPanel();
        clientPanal = new javax.swing.JPanel();
        salePanal = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        staffPannel = new javax.swing.JPanel();
        rentPannel = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Carrefour - Multinational Corporation (Client)");
        setPreferredSize(new java.awt.Dimension(913, 700));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setPreferredSize(new java.awt.Dimension(913, 100));
        jPanel2.setLayout(new java.awt.BorderLayout());

        sideMenu.setBackground(new java.awt.Color(21, 25, 28));
        sideMenu.setPreferredSize(new java.awt.Dimension(100, 700));

        Logo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/5a0c72729642de34b6b65ce7.png"))); // NOI18N
        Logo.setPreferredSize(new java.awt.Dimension(140, 100));

        homeLable.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        homeLable.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/home_35px.png"))); // NOI18N
        homeLable.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        homeLable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                homeLableMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                homeLableMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                homeLableMouseExited(evt);
            }
        });

        payLable.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        payLable.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/req_35px.png"))); // NOI18N
        payLable.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        payLable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                payLableMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                payLableMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                payLableMouseExited(evt);
            }
        });

        saleLable.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        saleLable.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/warehouse_35px.png"))); // NOI18N
        saleLable.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        saleLable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                saleLableMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                saleLableMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                saleLableMouseExited(evt);
            }
        });

        aboutLable.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        aboutLable.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/total_sales_35px.png"))); // NOI18N
        aboutLable.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        aboutLable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                aboutLableMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                aboutLableMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                aboutLableMouseExited(evt);
            }
        });

        mailLable.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        mailLable.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/email_35px.png"))); // NOI18N
        mailLable.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        mailLable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mailLableMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                mailLableMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                mailLableMouseExited(evt);
            }
        });

        generalLable.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        generalLable.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/group_35px.png"))); // NOI18N
        generalLable.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        generalLable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                generalLableMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                generalLableMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                generalLableMouseExited(evt);
            }
        });

        lhome.setFont(new java.awt.Font("Tahoma", 2, 11)); // NOI18N
        lhome.setForeground(new java.awt.Color(255, 0, 0));

        lmail.setFont(new java.awt.Font("Tahoma", 2, 11)); // NOI18N
        lmail.setForeground(new java.awt.Color(255, 0, 0));

        lreq.setFont(new java.awt.Font("Tahoma", 2, 11)); // NOI18N
        lreq.setForeground(new java.awt.Color(255, 0, 0));

        lclient.setFont(new java.awt.Font("Tahoma", 2, 11)); // NOI18N
        lclient.setForeground(new java.awt.Color(255, 0, 0));

        lshop.setFont(new java.awt.Font("Tahoma", 2, 11)); // NOI18N
        lshop.setForeground(new java.awt.Color(255, 0, 0));

        lsale.setFont(new java.awt.Font("Tahoma", 2, 11)); // NOI18N
        lsale.setForeground(new java.awt.Color(255, 0, 0));

        stafflabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/staff_35px.png"))); // NOI18N
        stafflabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        stafflabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                stafflabelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                stafflabelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                stafflabelMouseExited(evt);
            }
        });

        lstaff.setFont(new java.awt.Font("Tahoma", 2, 11)); // NOI18N
        lstaff.setForeground(new java.awt.Color(255, 0, 0));

        jLabel50.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/coins_35px.png"))); // NOI18N
        jLabel50.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel50.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel50MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel50MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel50MouseExited(evt);
            }
        });

        lrent.setFont(new java.awt.Font("Tahoma", 2, 11)); // NOI18N
        lrent.setForeground(new java.awt.Color(255, 0, 0));

        javax.swing.GroupLayout sideMenuLayout = new javax.swing.GroupLayout(sideMenu);
        sideMenu.setLayout(sideMenuLayout);
        sideMenuLayout.setHorizontalGroup(
            sideMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(homeLable, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(mailLable, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(payLable, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(Logo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(saleLable, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(generalLable, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(lhome, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(lmail, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(lreq, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(lclient, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(lshop, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(aboutLable, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(lsale, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, sideMenuLayout.createSequentialGroup()
                .addContainerGap(37, Short.MAX_VALUE)
                .addGroup(sideMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, sideMenuLayout.createSequentialGroup()
                        .addComponent(lrent, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addComponent(jLabel50)
                    .addComponent(lstaff, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, sideMenuLayout.createSequentialGroup()
                        .addComponent(stafflabel)
                        .addGap(28, 28, 28))))
        );
        sideMenuLayout.setVerticalGroup(
            sideMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sideMenuLayout.createSequentialGroup()
                .addComponent(Logo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(63, 63, 63)
                .addComponent(homeLable)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lhome)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(mailLable)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lmail)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(payLable)
                .addGap(11, 11, 11)
                .addComponent(lreq)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(generalLable)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lclient)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(saleLable)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lshop)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(aboutLable, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lsale)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(stafflabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lstaff, javax.swing.GroupLayout.PREFERRED_SIZE, 7, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel50)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lrent)
                .addContainerGap())
        );

        jPanel2.add(sideMenu, java.awt.BorderLayout.WEST);

        centerBackground.setBackground(new java.awt.Color(36, 40, 44));
        centerBackground.setLayout(new java.awt.BorderLayout());
        centerBackground.add(jLabel1, java.awt.BorderLayout.CENTER);

        jPanel1.setBackground(new java.awt.Color(36, 40, 44));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(20, 25, 28)));
        jPanel1.setPreferredSize(new java.awt.Dimension(813, 150));
        jPanel1.setLayout(new java.awt.GridLayout(1, 0));

        jPanel5.setBackground(new java.awt.Color(20, 25, 28));

        nameLable.setBackground(new java.awt.Color(182, 182, 179));
        nameLable.setFont(new java.awt.Font("Perpetua Titling MT", 0, 22)); // NOI18N
        nameLable.setForeground(new java.awt.Color(182, 182, 179));
        nameLable.setText("Haider ali");

        nameLable1.setBackground(new java.awt.Color(182, 182, 179));
        nameLable1.setFont(new java.awt.Font("Perpetua Titling MT", 0, 14)); // NOI18N
        nameLable1.setForeground(new java.awt.Color(182, 182, 179));
        nameLable1.setText("MGr-137");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(nameLable, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nameLable1, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 25, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(nameLable)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(nameLable1)
                .addContainerGap(87, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel5);

        jPanel9.setBackground(new java.awt.Color(20, 25, 28));

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 28)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 0, 0));
        jLabel11.setText("( HOME )");

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel9Layout.createSequentialGroup()
                .addContainerGap(46, Short.MAX_VALUE)
                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel9Layout.createSequentialGroup()
                .addContainerGap(70, Short.MAX_VALUE)
                .addComponent(jLabel11)
                .addGap(44, 44, 44))
        );

        jPanel1.add(jPanel9);

        jPanel10.setBackground(new java.awt.Color(20, 25, 28));

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/dp_50px.png"))); // NOI18N

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel10Layout.createSequentialGroup()
                .addContainerGap(227, Short.MAX_VALUE)
                .addComponent(jLabel10)
                .addContainerGap())
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel10)
                .addContainerGap(87, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel10);

        centerBackground.add(jPanel1, java.awt.BorderLayout.PAGE_START);

        jPanel3.setPreferredSize(new java.awt.Dimension(813, 250));
        jPanel3.setLayout(new java.awt.BorderLayout());
        jPanel3.add(jLabel2, java.awt.BorderLayout.CENTER);

        jPanel6.setBackground(new java.awt.Color(36, 40, 44));
        jPanel6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(20, 25, 28)));
        jPanel6.setPreferredSize(new java.awt.Dimension(815, 70));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/icons8_location_off_50px_1.png"))); // NOI18N

        jLabel3.setBackground(new java.awt.Color(182, 182, 179));
        jLabel3.setForeground(new java.awt.Color(182, 182, 179));
        jLabel3.setText("Nabeel Yousaf");

        jLabel5.setBackground(new java.awt.Color(182, 182, 179));
        jLabel5.setForeground(new java.awt.Color(182, 182, 179));
        jLabel5.setText("2020-CS-103");

        jLabel6.setBackground(new java.awt.Color(182, 182, 179));
        jLabel6.setForeground(new java.awt.Color(182, 182, 179));
        jLabel6.setText("Haider Ali");

        jLabel7.setBackground(new java.awt.Color(182, 182, 179));
        jLabel7.setForeground(new java.awt.Color(182, 182, 179));
        jLabel7.setText("2020-CS-137");

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/icons8_location_off_50px_1.png"))); // NOI18N

        tableAdd.setBackground(new java.awt.Color(182, 182, 179));
        tableAdd.setFont(new java.awt.Font("Perpetua", 0, 18)); // NOI18N
        tableAdd.setForeground(new java.awt.Color(241, 62, 51));

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(66, 66, 66)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel5))
                .addGap(126, 126, 126)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7))
                .addGap(126, 126, 126)
                .addComponent(tableAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(201, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel5)
                        .addGap(6, 6, 6))
                    .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(tableAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        jPanel3.add(jPanel6, java.awt.BorderLayout.PAGE_END);

        addProductPanal.setBackground(new java.awt.Color(36, 40, 44));
        addProductPanal.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(20, 25, 28)));
        addProductPanal.setLayout(new java.awt.GridLayout(1, 0));

        productTablePanal.setBackground(new java.awt.Color(36, 40, 44));
        productTablePanal.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(20, 25, 28)));
        productTablePanal.setLayout(new java.awt.BorderLayout());

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        productTablePanal.add(jScrollPane1, java.awt.BorderLayout.PAGE_START);

        addProductPanal.add(productTablePanal);

        jPanel3.add(addProductPanal, java.awt.BorderLayout.CENTER);

        centerBackground.add(jPanel3, java.awt.BorderLayout.PAGE_END);

        jPanel4.setBackground(new java.awt.Color(36, 40, 44));
        jPanel4.setPreferredSize(new java.awt.Dimension(200, 365));
        jPanel4.setLayout(new java.awt.GridLayout(1, 0));

        SearchPannel.setBackground(new java.awt.Color(20, 25, 28));
        SearchPannel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(20, 25, 28)));
        SearchPannel.setLayout(new java.awt.BorderLayout());

        tableToAdd.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        tableToAdd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/icons8_click_&_collect_35px_2.png"))); // NOI18N
        tableToAdd.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        tableToAdd.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableToAddMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                tableToAddMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                tableToAddMouseExited(evt);
            }
        });
        SearchPannel.add(tableToAdd, java.awt.BorderLayout.PAGE_END);

        viewTable.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        viewTable.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/icons8_table_properties_35px.png"))); // NOI18N
        viewTable.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        viewTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                viewTableMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                viewTableMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                viewTableMouseExited(evt);
            }
        });
        SearchPannel.add(viewTable, java.awt.BorderLayout.PAGE_END);

        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("                          Information");
        SearchPannel.add(jLabel12, java.awt.BorderLayout.PAGE_START);

        jLabel37.setText("Name :");

        jLabel38.setText("Email :");

        jLabel39.setText("Phone :");

        jLabel40.setText("Cnic :");

        jLabel41.setText("DOB :");

        jLabel42.setText("Gender :");

        jLabel43.setText("Shop request :");

        jLabel44.setText("Address :");

        jLabel45.setText("                         Information");
        jLabel45.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        viewTable3.setBackground(new java.awt.Color(102, 102, 102));
        viewTable3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        viewTable3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/icons8_table_properties_35px.png"))); // NOI18N
        viewTable3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        viewTable3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                viewTable1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                viewTable1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                viewTable1MouseExited(evt);
            }
        });

        javax.swing.GroupLayout infoPaneLayout = new javax.swing.GroupLayout(infoPane);
        infoPane.setLayout(infoPaneLayout);
        infoPaneLayout.setHorizontalGroup(
            infoPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel45, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(infoPaneLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(infoPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(infoPaneLayout.createSequentialGroup()
                        .addComponent(jLabel44)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(viewTable3, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(infoPaneLayout.createSequentialGroup()
                        .addGroup(infoPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel37)
                            .addComponent(jLabel38)
                            .addComponent(jLabel39)
                            .addComponent(jLabel40)
                            .addComponent(jLabel41)
                            .addComponent(jLabel42)
                            .addComponent(jLabel43))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        infoPaneLayout.setVerticalGroup(
            infoPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(infoPaneLayout.createSequentialGroup()
                .addComponent(jLabel45)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel37)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel38)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel39)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel40)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel41)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel42)
                .addGap(9, 9, 9)
                .addComponent(jLabel43)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(infoPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel44)
                    .addComponent(viewTable3))
                .addContainerGap(114, Short.MAX_VALUE))
        );

        SearchPannel.add(infoPane, java.awt.BorderLayout.CENTER);

        jLabel51.setText("Name :");

        jLabel52.setText("Email :");

        jLabel54.setText("Phone :");

        jLabel55.setText("Cliend Id :");

        jLabel56.setText("Shop Id :");

        jLabel57.setText("Rent :");

        jLabel58.setText("Status :");

        jButton1.setText("Go");

        javax.swing.GroupLayout searchRentLayout = new javax.swing.GroupLayout(searchRent);
        searchRent.setLayout(searchRentLayout);
        searchRentLayout.setHorizontalGroup(
            searchRentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(searchRentLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(searchRentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel51)
                    .addComponent(jLabel52)
                    .addComponent(jLabel54)
                    .addComponent(jLabel55)
                    .addComponent(jLabel56)
                    .addComponent(jLabel57)
                    .addComponent(jLabel58))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(searchRentLayout.createSequentialGroup()
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        searchRentLayout.setVerticalGroup(
            searchRentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(searchRentLayout.createSequentialGroup()
                .addGroup(searchRentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addGap(2, 2, 2)
                .addComponent(jLabel51)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel52)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel54)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel55)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel56)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel57)
                .addGap(9, 9, 9)
                .addComponent(jLabel58)
                .addContainerGap(152, Short.MAX_VALUE))
        );

        SearchPannel.add(searchRent, java.awt.BorderLayout.CENTER);

        jPanel4.add(SearchPannel);

        centerBackground.add(jPanel4, java.awt.BorderLayout.LINE_END);

        homePanal.setBackground(new java.awt.Color(204, 204, 204));
        homePanal.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(20, 25, 28)));
        homePanal.setAutoscrolls(true);
        homePanal.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        homePanal.setPreferredSize(new java.awt.Dimension(500, 365));
        homePanal.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                homePanalMouseEntered(evt);
            }
        });
        homePanal.setLayout(new java.awt.BorderLayout());

        mailPanal.setBackground(new java.awt.Color(255, 51, 153));
        mailPanal.setAutoscrolls(true);
        mailPanal.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        mailPanal.setPreferredSize(new java.awt.Dimension(500, 365));

        ename4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        ename4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ename4ActionPerformed(evt);
            }
        });

        jLabel46.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        jLabel46.setText("Email Id :");

        jLabel47.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        jLabel47.setText("Subject :");

        ename5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        ename5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ename5ActionPerformed(evt);
            }
        });

        jLabel48.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        jLabel48.setText("Content :");

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jTextArea1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jScrollPane2.setViewportView(jTextArea1);

        jButton17.setBackground(new java.awt.Color(153, 153, 153));
        jButton17.setText("send");
        jButton17.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton17ActionPerformed(evt);
            }
        });

        jLabel49.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/forward_arrow_25px.png"))); // NOI18N

        javax.swing.GroupLayout mailPanalLayout = new javax.swing.GroupLayout(mailPanal);
        mailPanal.setLayout(mailPanalLayout);
        mailPanalLayout.setHorizontalGroup(
            mailPanalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mailPanalLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(mailPanalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(mailPanalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel46)
                        .addComponent(jLabel47))
                    .addGroup(mailPanalLayout.createSequentialGroup()
                        .addComponent(jLabel48)
                        .addGap(7, 7, 7)))
                .addGap(18, 18, 18)
                .addGroup(mailPanalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ename5, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ename4, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(mailPanalLayout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(44, 44, 44)
                        .addComponent(jLabel49)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton17)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        mailPanalLayout.setVerticalGroup(
            mailPanalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mailPanalLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(mailPanalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel49)
                    .addGroup(mailPanalLayout.createSequentialGroup()
                        .addGroup(mailPanalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel46)
                            .addComponent(ename4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(mailPanalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel47)
                            .addComponent(ename5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(mailPanalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(mailPanalLayout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(jLabel48))
                            .addGroup(mailPanalLayout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(jButton17, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        homePanal.add(mailPanal, java.awt.BorderLayout.CENTER);

        requestsPanal.setBackground(new java.awt.Color(255, 2, 2));
        requestsPanal.setAutoscrolls(true);
        requestsPanal.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        requestsPanal.setPreferredSize(new java.awt.Dimension(500, 365));

        jLabel13.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        jLabel13.setText("Name :");

        ename.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        ename.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enameActionPerformed(evt);
            }
        });

        jLabel14.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        jLabel14.setText("Email :");

        jLabel15.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        jLabel15.setText("Client Id :");

        jLabel16.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        jLabel16.setText("Password :");

        ename1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        ename1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ename1ActionPerformed(evt);
            }
        });

        ename2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        ename2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ename2ActionPerformed(evt);
            }
        });

        ename3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        ename3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ename3ActionPerformed(evt);
            }
        });

        jButton15.setBackground(new java.awt.Color(153, 153, 153));
        jButton15.setText("Accept");
        jButton15.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton15ActionPerformed(evt);
            }
        });

        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/task_completed_25px.png"))); // NOI18N

        jButton16.setBackground(new java.awt.Color(153, 153, 153));
        jButton16.setText("Reject");
        jButton16.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton16ActionPerformed(evt);
            }
        });

        jLabel26.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/delete_25px.png"))); // NOI18N

        javax.swing.GroupLayout requestsPanalLayout = new javax.swing.GroupLayout(requestsPanal);
        requestsPanal.setLayout(requestsPanalLayout);
        requestsPanalLayout.setHorizontalGroup(
            requestsPanalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(requestsPanalLayout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addGroup(requestsPanalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel16)
                    .addComponent(jLabel15)
                    .addGroup(requestsPanalLayout.createSequentialGroup()
                        .addGroup(requestsPanalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(requestsPanalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(requestsPanalLayout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addComponent(jLabel53))
                            .addGroup(requestsPanalLayout.createSequentialGroup()
                                .addGap(53, 53, 53)
                                .addGroup(requestsPanalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(ename1, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(ename, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(ename2, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(ename3, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, requestsPanalLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel17)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton15)
                .addGap(18, 18, 18)
                .addComponent(jLabel26)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton16)
                .addGap(3, 3, 3))
        );
        requestsPanalLayout.setVerticalGroup(
            requestsPanalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(requestsPanalLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(requestsPanalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(requestsPanalLayout.createSequentialGroup()
                        .addGroup(requestsPanalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel13)
                            .addComponent(ename, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(16, 16, 16)
                        .addGroup(requestsPanalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel14)
                            .addComponent(ename1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(requestsPanalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel15)
                            .addComponent(ename2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(requestsPanalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel16)
                            .addComponent(ename3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(requestsPanalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel17)
                            .addComponent(jButton15, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, requestsPanalLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(requestsPanalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel26, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jButton16, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(16, 16, 16)
                .addComponent(jLabel53, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(67, 67, 67))
        );

        homePanal.add(requestsPanal, java.awt.BorderLayout.CENTER);

        shopPanal.setBackground(new java.awt.Color(0, 0, 255));
        shopPanal.setAutoscrolls(true);
        shopPanal.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        shopPanal.setPreferredSize(new java.awt.Dimension(500, 365));

        javax.swing.GroupLayout shopPanalLayout = new javax.swing.GroupLayout(shopPanal);
        shopPanal.setLayout(shopPanalLayout);
        shopPanalLayout.setHorizontalGroup(
            shopPanalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        shopPanalLayout.setVerticalGroup(
            shopPanalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        homePanal.add(shopPanal, java.awt.BorderLayout.CENTER);

        clientPanal.setBackground(new java.awt.Color(200, 100, 1));
        clientPanal.setAutoscrolls(true);
        clientPanal.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        clientPanal.setPreferredSize(new java.awt.Dimension(500, 365));

        javax.swing.GroupLayout clientPanalLayout = new javax.swing.GroupLayout(clientPanal);
        clientPanal.setLayout(clientPanalLayout);
        clientPanalLayout.setHorizontalGroup(
            clientPanalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        clientPanalLayout.setVerticalGroup(
            clientPanalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        homePanal.add(clientPanal, java.awt.BorderLayout.CENTER);

        salePanal.setBackground(new java.awt.Color(150, 150, 4));
        salePanal.setAutoscrolls(true);
        salePanal.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        salePanal.setPreferredSize(new java.awt.Dimension(500, 365));

        javax.swing.GroupLayout salePanalLayout = new javax.swing.GroupLayout(salePanal);
        salePanal.setLayout(salePanalLayout);
        salePanalLayout.setHorizontalGroup(
            salePanalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        salePanalLayout.setVerticalGroup(
            salePanalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        homePanal.add(salePanal, java.awt.BorderLayout.CENTER);

        jLabel9.setText("jLabel9");
        homePanal.add(jLabel9, java.awt.BorderLayout.PAGE_START);

        staffPannel.setBackground(new java.awt.Color(0, 204, 204));
        staffPannel.setAutoscrolls(true);
        staffPannel.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        staffPannel.setPreferredSize(new java.awt.Dimension(500, 365));

        javax.swing.GroupLayout staffPannelLayout = new javax.swing.GroupLayout(staffPannel);
        staffPannel.setLayout(staffPannelLayout);
        staffPannelLayout.setHorizontalGroup(
            staffPannelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        staffPannelLayout.setVerticalGroup(
            staffPannelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        homePanal.add(staffPannel, java.awt.BorderLayout.CENTER);

        rentPannel.setBackground(new java.awt.Color(102, 204, 0));
        rentPannel.setAutoscrolls(true);
        rentPannel.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        rentPannel.setPreferredSize(new java.awt.Dimension(500, 365));

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Name", "Client Id", "Shop Id", "Rent", "Status"
            }
        ));
        jScrollPane3.setViewportView(jTable2);

        javax.swing.GroupLayout rentPannelLayout = new javax.swing.GroupLayout(rentPannel);
        rentPannel.setLayout(rentPannelLayout);
        rentPannelLayout.setHorizontalGroup(
            rentPannelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 661, Short.MAX_VALUE)
        );
        rentPannelLayout.setVerticalGroup(
            rentPannelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(rentPannelLayout.createSequentialGroup()
                .addGap(79, 79, 79)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(179, Short.MAX_VALUE))
        );

        homePanal.add(rentPannel, java.awt.BorderLayout.CENTER);

        centerBackground.add(homePanal, java.awt.BorderLayout.CENTER);

        jPanel2.add(centerBackground, java.awt.BorderLayout.CENTER);

        getContentPane().add(jPanel2, java.awt.BorderLayout.CENTER);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void homeLableMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_homeLableMouseEntered
        // TODO add your handling code here:
        homeLable.setBackground(new Color(36,40,44));
        homeLable.setOpaque(true);
        lhome.setText("Home");
        
        
    }//GEN-LAST:event_homeLableMouseEntered

    private void homeLableMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_homeLableMouseExited
        // TODO add your handling code here:
        
        
        lhome.setText("");
        homeLable.setBackground(new Color(20,25,28));
        homeLable.setOpaque(false);
        
    }//GEN-LAST:event_homeLableMouseExited

    private void mailLableMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mailLableMouseEntered
        // TODO add your handling code here:
        mailLable.setBackground(new Color(36,40,44));
        mailLable.setOpaque(true);
        lmail.setText("Email");
    }//GEN-LAST:event_mailLableMouseEntered

    private void mailLableMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mailLableMouseExited
        // TODO add your handling code here:
        mailLable.setBackground(new Color(20,25,28));
        mailLable.setOpaque(false);
        lmail.setText("");
    }//GEN-LAST:event_mailLableMouseExited

    private void generalLableMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_generalLableMouseEntered
        // TODO add your handling code here:
        generalLable.setBackground(new Color(36,40,44));
        generalLable.setOpaque(true);
        lclient.setText("Client");
    }//GEN-LAST:event_generalLableMouseEntered

    private void generalLableMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_generalLableMouseExited
        // TODO add your handling code here:
        generalLable.setBackground(new Color(20,25,28));
        generalLable.setOpaque(false);
        lclient.setText("");
    }//GEN-LAST:event_generalLableMouseExited

    private void saleLableMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_saleLableMouseEntered
        // TODO add your handling code here:
        saleLable.setBackground(new Color(36,40,44));
        saleLable.setOpaque(true);
        lshop.setText("Shops");
    }//GEN-LAST:event_saleLableMouseEntered

    private void saleLableMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_saleLableMouseExited
        // TODO add your handling code here:
        saleLable.setBackground(new Color(20,25,28));
        saleLable.setOpaque(false);
        lshop.setText("");
    }//GEN-LAST:event_saleLableMouseExited

    private void aboutLableMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_aboutLableMouseEntered
        // TODO add your handling code here:
        aboutLable.setBackground(new Color(36,40,44));
        aboutLable.setOpaque(true);
        lsale.setText("Sales");
    }//GEN-LAST:event_aboutLableMouseEntered

    private void aboutLableMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_aboutLableMouseExited
        // TODO add your handling code here:
        aboutLable.setBackground(new Color(20,25,28));
        aboutLable.setOpaque(false);
        
        lsale.setText("");
    }//GEN-LAST:event_aboutLableMouseExited

    private void homeLableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_homeLableMouseClicked
        // TODO add your handling code here:
//        removing panals
        SearchPannel.removeAll();
        SearchPannel.repaint();
        SearchPannel.revalidate();
        homePanal.removeAll();
        homePanal.repaint();
        homePanal.revalidate();
        jLabel11.setText("( HOME )");
        
    }//GEN-LAST:event_homeLableMouseClicked

    private void mailLableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mailLableMouseClicked
        // TODO add your handling code here:
        homePanal.removeAll();
        homePanal.repaint();
        homePanal.revalidate();
        jLabel11.setText("( EMAIL )");
        homePanal.add(mailPanal);
        homePanal.repaint();
        homePanal.revalidate();
        
        SearchPannel.removeAll();
        SearchPannel.repaint();
        SearchPannel.revalidate();
        
    }//GEN-LAST:event_mailLableMouseClicked

    private void generalLableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_generalLableMouseClicked
        // TODO add your handling code here:
        homePanal.removeAll();
        homePanal.repaint();
        homePanal.revalidate();
        
        SearchPannel.removeAll();
        SearchPannel.repaint();
        SearchPannel.revalidate();
        //Adding panals
        homePanal.add(clientPanal);
        homePanal.repaint();
        homePanal.revalidate();
        jLabel11.setText("( CLIENTS )");
    }//GEN-LAST:event_generalLableMouseClicked

    private void saleLableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_saleLableMouseClicked
        // TODO add your handling code here:
        homePanal.removeAll();
        homePanal.repaint();
        homePanal.revalidate();
        
        SearchPannel.removeAll();
        SearchPannel.repaint();
        SearchPannel.revalidate();
        //Adding panals
        homePanal.add(shopPanal);
        homePanal.repaint();
        homePanal.revalidate();
        jLabel11.setText("( SHOPS )");
    }//GEN-LAST:event_saleLableMouseClicked

    private void aboutLableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_aboutLableMouseClicked
        // TODO add your handling code here:
        homePanal.removeAll();
        homePanal.repaint();
        homePanal.revalidate();
        
        SearchPannel.removeAll();
        SearchPannel.repaint();
        SearchPannel.revalidate();
        //Adding panals
        homePanal.add(salePanal);
        homePanal.repaint();
        homePanal.revalidate();
        jLabel11.setText("( SALES )");
    }//GEN-LAST:event_aboutLableMouseClicked

    private void tableToAddMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableToAddMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_tableToAddMouseExited

    private void tableToAddMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableToAddMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_tableToAddMouseEntered

    private void tableToAddMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableToAddMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_tableToAddMouseClicked

    private void viewTableMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_viewTableMouseExited
        // TODO add your handling code here:
        viewTable.setBackground(new Color(20,25,28));
        viewTable.setOpaque(false);
        tableAdd.setText("");
    }//GEN-LAST:event_viewTableMouseExited

    private void viewTableMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_viewTableMouseEntered
        // TODO add your handling code here:
        viewTable.setBackground(new Color(36,40,44));
        viewTable.setOpaque(true);
        tableAdd.setText("View Table");

    }//GEN-LAST:event_viewTableMouseEntered

    private void viewTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_viewTableMouseClicked
        // TODO add your handling code here:
        productTablePanal.setVisible(true);
        viewTable.setVisible(false);
        addProductPanal.add(productTablePanal);
        addProductPanal.repaint();
        addProductPanal.revalidate();
        tableToAdd.setVisible(true);
        tableToAdd.setEnabled(true);
    }//GEN-LAST:event_viewTableMouseClicked

    private void payLableMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_payLableMouseExited
        // TODO add your handling code here:
        payLable.setBackground(new Color(20,25,28));
        payLable.setOpaque(false);
        lreq.setText("");

    }//GEN-LAST:event_payLableMouseExited

    private void payLableMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_payLableMouseEntered
        // TODO add your handling code here:
        payLable.setBackground(new Color(36,40,44));
        payLable.setOpaque(true);
        lreq.setText("Requests");
    }//GEN-LAST:event_payLableMouseEntered

    private void payLableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_payLableMouseClicked
        // TODO add your handling code here:
        SearchPannel.removeAll();
        SearchPannel.repaint();
        SearchPannel.revalidate();
        
        homePanal.removeAll();
        homePanal.repaint();
        homePanal.revalidate();
        //Adding panals
        homePanal.add(requestsPanal);
        homePanal.repaint();
        homePanal.revalidate();
        jLabel11.setText("( REQUESTS )");
        
        //Adding panals
        SearchPannel.add(infoPane);
        SearchPannel.repaint();
        SearchPannel.revalidate();
        
    }//GEN-LAST:event_payLableMouseClicked

    private void homePanalMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_homePanalMouseEntered
        // TODO add your handling code here:
        
    }//GEN-LAST:event_homePanalMouseEntered

    private void stafflabelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_stafflabelMouseEntered
        // TODO add your handling code here:
        lstaff.setText("Staff");
    }//GEN-LAST:event_stafflabelMouseEntered

    private void enameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_enameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_enameActionPerformed

    private void ename1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ename1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ename1ActionPerformed

    private void ename2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ename2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ename2ActionPerformed

    private void ename3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ename3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ename3ActionPerformed

    private void jButton15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton15ActionPerformed
        // TODO add your handling code here:
       

    }//GEN-LAST:event_jButton15ActionPerformed

    private void jButton16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton16ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton16ActionPerformed

    private void stafflabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_stafflabelMouseClicked
        // TODO add your handling code here:
        jLabel11.setText("( STAFF )");
        homePanal.removeAll();
        homePanal.repaint();
        homePanal.revalidate();
        
        SearchPannel.removeAll();
        SearchPannel.repaint();
        SearchPannel.revalidate();
        //Adding panals
        homePanal.add(staffPannel);
        homePanal.repaint();
        homePanal.revalidate();
    }//GEN-LAST:event_stafflabelMouseClicked

    private void stafflabelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_stafflabelMouseExited
        // TODO add your handling code here:
        lstaff.setText("");
    }//GEN-LAST:event_stafflabelMouseExited

    private void viewTable1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_viewTable1MouseExited
        // TODO add your handling code here:
        viewTable.setBackground(new Color(20,25,28));
        viewTable.setOpaque(false);
        tableAdd.setText("");
    }//GEN-LAST:event_viewTable1MouseExited

    private void viewTable1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_viewTable1MouseEntered
        // TODO add your handling code here:
        viewTable.setBackground(new Color(36,40,44));
        viewTable.setOpaque(true);
        tableAdd.setText("View Table");
    }//GEN-LAST:event_viewTable1MouseEntered

    private void viewTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_viewTable1MouseClicked
        // TODO add your handling code here:
        productTablePanal.setVisible(true);
        viewTable.setVisible(false);
        addProductPanal.add(productTablePanal);
        addProductPanal.repaint();
        addProductPanal.revalidate();
        tableToAdd.setVisible(true);
        tableToAdd.setEnabled(true);
    }//GEN-LAST:event_viewTable1MouseClicked

    private void ename4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ename4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ename4ActionPerformed

    private void ename5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ename5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ename5ActionPerformed

    private void jButton17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton17ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton17ActionPerformed

    private void jLabel50MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel50MouseEntered
        // TODO add your handling code here:
        lrent.setText("Rent");
    }//GEN-LAST:event_jLabel50MouseEntered

    private void jLabel50MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel50MouseExited
        // TODO add your handling code here:
        lrent.setText("");
    }//GEN-LAST:event_jLabel50MouseExited

    private void jLabel50MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel50MouseClicked
        // TODO add your handling code here:
        jLabel11.setText("( RENT )");
        homePanal.removeAll();
        homePanal.repaint();
        homePanal.revalidate();
        
        SearchPannel.removeAll();
        SearchPannel.repaint();
        SearchPannel.revalidate();
        //Adding panals
        homePanal.add(rentPannel);
        homePanal.repaint();
        homePanal.revalidate();
        
        SearchPannel.add(searchRent);
        SearchPannel.repaint();
        SearchPannel.revalidate();
    }//GEN-LAST:event_jLabel50MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ManagerForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ManagerForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ManagerForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ManagerForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ManagerForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Logo;
    private javax.swing.JPanel SearchPannel;
    private javax.swing.JLabel aboutLable;
    private javax.swing.JPanel addProductPanal;
    private javax.swing.JPanel centerBackground;
    private javax.swing.JPanel clientPanal;
    private javax.swing.JTextField ename;
    private javax.swing.JTextField ename1;
    private javax.swing.JTextField ename2;
    private javax.swing.JTextField ename3;
    private javax.swing.JTextField ename4;
    private javax.swing.JTextField ename5;
    private javax.swing.JLabel generalLable;
    private javax.swing.JLabel homeLable;
    private javax.swing.JPanel homePanal;
    private javax.swing.JPanel infoPane;
    private javax.swing.JPanel infoPane1;
    private javax.swing.JPanel infoPane2;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton15;
    private javax.swing.JButton jButton16;
    private javax.swing.JButton jButton17;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel47;
    private javax.swing.JLabel jLabel48;
    private javax.swing.JLabel jLabel49;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel50;
    private javax.swing.JLabel jLabel51;
    private javax.swing.JLabel jLabel52;
    private javax.swing.JLabel jLabel53;
    private javax.swing.JLabel jLabel54;
    private javax.swing.JLabel jLabel55;
    private javax.swing.JLabel jLabel56;
    private javax.swing.JLabel jLabel57;
    private javax.swing.JLabel jLabel58;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JLabel lclient;
    private javax.swing.JLabel lhome;
    private javax.swing.JLabel lmail;
    private javax.swing.JLabel lrent;
    private javax.swing.JLabel lreq;
    private javax.swing.JLabel lsale;
    private javax.swing.JLabel lshop;
    private javax.swing.JLabel lstaff;
    private javax.swing.JLabel mailLable;
    private javax.swing.JPanel mailPanal;
    private javax.swing.JLabel nameLable;
    private javax.swing.JLabel nameLable1;
    private javax.swing.JLabel payLable;
    private javax.swing.JPanel productTablePanal;
    private javax.swing.JPanel rentPannel;
    private javax.swing.JPanel requestsPanal;
    private javax.swing.JLabel saleLable;
    private javax.swing.JPanel salePanal;
    private javax.swing.JPanel searchRent;
    private javax.swing.JPanel shopPanal;
    private javax.swing.JPanel sideMenu;
    private javax.swing.JPanel staffPannel;
    private javax.swing.JLabel stafflabel;
    private javax.swing.JLabel tableAdd;
    private javax.swing.JLabel tableToAdd;
    private javax.swing.JLabel viewTable;
    private javax.swing.JLabel viewTable1;
    private javax.swing.JLabel viewTable2;
    private javax.swing.JLabel viewTable3;
    // End of variables declaration//GEN-END:variables
}
